# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/eripish_la_gallineta/Desktop/universidad/2017-2/arq/git_grupo/2017-2-G12/carpeta proyecto/Proyecto Base/Proyecto Base.cache/wt} [current_project]
set_property parent.project_path {C:/Users/eripish_la_gallineta/Desktop/universidad/2017-2/arq/git_grupo/2017-2-G12/carpeta proyecto/Proyecto Base/Proyecto Base.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/eripish_la_gallineta/Desktop/universidad/2017-2/arq/git_grupo/2017-2-G12/carpeta proyecto/Proyecto Base/Proyecto Base.srcs/sources_1/new/Clock_Divider.vhd}
  {C:/Users/eripish_la_gallineta/Desktop/universidad/2017-2/arq/git_grupo/2017-2-G12/carpeta proyecto/Proyecto Base/Proyecto Base.srcs/sources_1/new/Debouncer.vhd}
  {C:/Users/eripish_la_gallineta/Desktop/universidad/2017-2/arq/git_grupo/2017-2-G12/carpeta proyecto/Proyecto Base/Proyecto Base.srcs/sources_1/new/Display_Controller.vhd}
  {C:/Users/eripish_la_gallineta/Desktop/universidad/2017-2/arq/git_grupo/2017-2-G12/carpeta proyecto/Proyecto Base/Proyecto Base.srcs/sources_1/new/Reg.vhd}
  {C:/Users/eripish_la_gallineta/Desktop/universidad/2017-2/arq/git_grupo/2017-2-G12/carpeta proyecto/Proyecto Base/Proyecto Base.srcs/sources_1/new/Basys3.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/eripish_la_gallineta/Desktop/universidad/2017-2/arq/git_grupo/2017-2-G12/carpeta proyecto/Proyecto Base/Proyecto Base.srcs/constrs_1/new/Basys3.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/eripish_la_gallineta/Desktop/universidad/2017-2/arq/git_grupo/2017-2-G12/carpeta proyecto/Proyecto Base/Proyecto Base.srcs/constrs_1/new/Basys3.xdc}}]


synth_design -top Basys3 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Basys3.dcp

catch { report_utilization -file Basys3_utilization_synth.rpt -pb Basys3_utilization_synth.pb }
